package academy.learnprogramming;

class DefaultConstructorDog {}

public class DefaultConstructor {

  public static void main(String[] args) {
    // default constructor is generated by the compiler if no constructor is defined
    new DefaultConstructorDog();
  }
}
